//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bandicoot.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bandicootDatabaseEntities : DbContext
    {
        public bandicootDatabaseEntities()
            : base("name=bandicootDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Achievement> Achievement { get; set; }
        public virtual DbSet<GameDetails> GameDetails { get; set; }
        public virtual DbSet<GameDetails_Stage> GameDetails_Stage { get; set; }
        public virtual DbSet<Platform> Platform { get; set; }
        public virtual DbSet<Player> Player { get; set; }
        public virtual DbSet<Record> Record { get; set; }
        public virtual DbSet<Stage> Stage { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
