//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bandicoot.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GameDetails()
        {
            this.Stage = new HashSet<Stage>();
        }
    
        public byte gameID { get; set; }
        public byte platformID { get; set; }
        public string title { get; set; }
    
        public virtual GameDetails_Stage GameDetails_Stage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stage> Stage { get; set; }
        public virtual Platform Platform { get; set; }
    }
}
